version: '3.3'
services:
  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre
      - POSTGRES_DB=test-task
    image: postgres:alpine
    ports:
      - 15433:5432

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_DATABASE=hashtranslator
